# -*- coding: utf-8 -*-
"""Mini task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEsQIjb-xRQ9b-o-P8g81ptxYsXXgRPG
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_csv("shopping_behavior_updated.csv")
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.countplot(x="Gender", data=df, palette="Set2")
plt.title("Gender Distribution (Countplot)")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df["Age"], bins=20, kde=True, color="black")
plt.title("Age Distribution (Histogram)")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x="Gender", y="Purchase Amount (USD)", data=df, palette="pastel")
plt.title("Purchase Amount by Gender (Boxplot)")
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap ")
plt.show()

plt.figure(figsize=(6,4))
sns.violinplot(x="Category", y="Purchase Amount (USD)", data=df, palette="muted")
plt.title("Purchase Amount by Category")
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
df["Gender"].value_counts().plot(kind="bar", color="teal")
plt.title("Gender Distribution Bar chart")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(6,4))
plt.hist(df["Age"], bins=20, color="yellow", edgecolor="black")
plt.title("Age Distribution Histogram")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(6,6))
df["Subscription Status"].value_counts().plot(kind="pie", autopct='%1.1f%%', startangle=90)
plt.title("Subscription Status pie chart")
plt.ylabel("")
plt.show()

plt.figure(figsize=(6,4))
df.groupby("Age")["Purchase Amount (USD)"].mean().plot(kind="line", marker="o", color="red")
plt.title("Average Purchase Amount by Age line plot")
plt.xlabel("Age")
plt.ylabel("Average Purchase Amount (USD)")
plt.show()

plt.figure(figsize=(8,6))


plt.scatter(
    df["Age"],
    df["Purchase Amount (USD)"],
    c=df["Gender"].map({"Male": "blue", "Female": "red"}),
    alpha=0.4, s=40, edgecolors="k"
)

plt.title("Age vs Purchase Amount by Gender", fontsize=14)
plt.xlabel("Age")
plt.ylabel("Purchase Amount (USD)")
plt.grid(True, linestyle="--", alpha=0.6)


import matplotlib.patches as mpatches
male_patch = mpatches.Patch(color="blue", label="Male")
female_patch = mpatches.Patch(color="red", label="Female")
plt.legend(handles=[male_patch, female_patch])

plt.show()